import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../theme';

export const communitiesStyles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: colors.bg },
    list: { paddingBottom: 100 },
    header: { paddingTop: spacing.md },
    topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: spacing.lg, marginBottom: spacing.md },
    userInfo: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
    avatarPlaceholder: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.primary + '20', alignItems: 'center', justifyContent: 'center' },
    headerTitle: { fontSize: 20, fontWeight: '800', color: colors.text },
    headerSubtitle: { fontSize: 12, color: colors.muted },
    searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', marginHorizontal: spacing.lg, paddingHorizontal: spacing.md, height: 48, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, marginBottom: spacing.md },
    searchIcon: { marginRight: spacing.sm },
    searchInput: { flex: 1, fontSize: 14, color: colors.text },
    categoryScroll: { paddingLeft: spacing.lg, paddingRight: spacing.sm, gap: spacing.sm, marginBottom: spacing.lg },
    categoryTag: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.border },
    categoryTagActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    categoryText: { fontSize: 12, fontWeight: '600', color: colors.muted },
    categoryTextActive: { color: '#fff' },
    sectionTitle: { fontSize: 18, fontWeight: '800', color: colors.text },
    card: { backgroundColor: '#fff', marginHorizontal: spacing.lg, marginBottom: spacing.md, padding: spacing.md, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 10, elevation: 2 },
    cardContent: { flexDirection: 'row', gap: spacing.md },
    cardImage: { width: 64, height: 64, borderRadius: radius.md },
    noImageContainer: { backgroundColor: colors.primary + '15', alignItems: 'center', justifyContent: 'center' },
    cardInfo: { flex: 1 },
    cardTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
    cardName: { fontSize: 15, fontWeight: '800', color: colors.text },
    cardSub: { fontSize: 12, color: colors.muted, marginTop: 2 },
    activeBadge: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    activeDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#22c55e' },
    activeText: { fontSize: 10, fontWeight: '600', color: '#22c55e' },
    cardBottomRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.sm },
    memberAvatars: { flexDirection: 'row', alignItems: 'center' },
    avatarStack: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: '#fff' },
    othersCount: { fontSize: 10, fontWeight: '700', color: colors.muted, marginLeft: 4 },
    joinButton: { backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 10, minWidth: 80, alignItems: 'center' },
    joinedButton: { backgroundColor: '#f1f5f9' },
    joinButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
    emptyText: { textAlign: 'center', color: colors.muted, marginTop: 40 },
    fab: { position: 'absolute', bottom: spacing.lg, right: spacing.lg, width: 56, height: 56, borderRadius: 16, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', shadowColor: colors.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 12, elevation: 8 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    modalContent: { backgroundColor: '#fff', borderTopLeftRadius: 32, borderTopRightRadius: 32, height: '85%', padding: spacing.lg },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.xl },
    modalTitle: { fontSize: 22, fontWeight: '800', color: colors.text },
    modalForm: { gap: spacing.lg, paddingBottom: 40 },
    photoSection: { alignItems: 'center', marginBottom: spacing.md },
    photoUploadBtn: { width: 100, height: 100, borderRadius: 50, backgroundColor: colors.primary + '10', borderWidth: 2, borderStyle: 'dashed', borderColor: colors.primary + '40', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
    uploadedPhoto: { width: '100%', height: '100%' },
    photoUploadText: { fontSize: 10, fontWeight: '700', color: colors.primary, marginTop: 4 },
    inputGroup: { gap: 8 },
    inputLabel: { fontSize: 14, fontWeight: '700', color: colors.text, marginLeft: 4 },
    input: { height: 56, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: 16, fontSize: 15 },
    textArea: { height: 100, paddingTop: 16, textAlignVertical: 'top' },
    submitBtn: { height: 56, backgroundColor: colors.primary, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', marginTop: 10 },
    submitBtnText: { color: '#FFF', fontSize: 16, fontWeight: '700' },
    btnDisabled: { backgroundColor: '#cbd5e1' },
    modalCategoryScroll: { gap: 8, paddingVertical: 4 },
    modalCatTag: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: radius.md, backgroundColor: '#f1f5f9', borderWidth: 1, borderColor: colors.border },
    modalCatTagActive: { backgroundColor: colors.primary, borderColor: colors.primary },
    modalCatText: { fontSize: 13, fontWeight: '600', color: colors.muted },
    modalCatTextActive: { color: '#fff' }
});
