import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../theme';

export const editScreenStyles = StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: '#F8FAFC' },
    header: {
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
        paddingHorizontal: spacing.lg, paddingVertical: spacing.md,
        backgroundColor: '#FFF', borderBottomWidth: 1, borderBottomColor: colors.border,
    },
    backIconBtn: {
        width: 40, height: 40, borderRadius: 20,
        backgroundColor: '#f1f5f9', alignItems: 'center', justifyContent: 'center',
    },
    headerTitle: { fontSize: 18, fontWeight: '800', color: colors.text },
    container: { paddingBottom: 100 },
    photoContainer: { padding: spacing.lg },
    photoRow: { flexDirection: 'row', gap: spacing.md, paddingVertical: 8 },
    addPhotoBtn: {
        width: 100, aspectRatio: 1, borderRadius: radius.md,
        backgroundColor: colors.primary + '08',
        borderWidth: 2, borderStyle: 'dashed', borderColor: colors.primary + '40',
        alignItems: 'center', justifyContent: 'center', gap: 4,
    },
    addPhotoText: { fontSize: 10, fontWeight: '700', color: colors.primary },
    photoThumb: { width: 100, aspectRatio: 1, borderRadius: radius.md, overflow: 'hidden' },
    thumbImage: { width: '100%', height: '100%' },
    coverBadge: {
        position: 'absolute', bottom: 0, left: 0, right: 0,
        backgroundColor: 'rgba(0,0,0,0.6)', paddingVertical: 2, alignItems: 'center',
    },
    coverBadgeActive: { backgroundColor: colors.primary },
    coverBadgeText: { color: '#FFF', fontSize: 9, fontWeight: '800' },
    deletePhoto: {
        position: 'absolute', top: 4, right: 4, width: 20, height: 20, borderRadius: 10,
        backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center',
    },
    form: { paddingHorizontal: spacing.lg, gap: spacing.lg },
    inputGroup: { gap: 6 },
    label: { fontSize: 13, fontWeight: '700', color: colors.text, marginLeft: 4 },
    input: {
        height: 50, backgroundColor: '#FFF', borderWidth: 1, borderColor: colors.border,
        borderRadius: radius.md, paddingHorizontal: 16, fontSize: 15, color: colors.text,
    },
    priceInputRow: { position: 'relative' },
    priceSymbol: { position: 'absolute', left: 16, top: 14, fontSize: 16, fontWeight: '700', color: colors.muted, zIndex: 1 },
    priceInput: { paddingLeft: 30, fontWeight: '700' },
    textArea: { height: 80, paddingTop: 12, textAlignVertical: 'top' },
    conditionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    conditionBtn: {
        flex: 1, minWidth: '45%', height: 40, borderRadius: radius.md,
        borderWidth: 1, borderColor: colors.border, backgroundColor: '#FFF',
        alignItems: 'center', justifyContent: 'center',
    },
    conditionBtnActive: { borderColor: colors.primary, backgroundColor: colors.primary + '08', borderWidth: 2 },
    conditionText: { fontSize: 12, fontWeight: '600', color: colors.muted },
    conditionTextActive: { color: colors.primary, fontWeight: '700' },
    statusText: { textAlign: 'center', color: '#ef4444', marginTop: 20, paddingHorizontal: spacing.lg },
    footer: {
        position: 'absolute', bottom: 0, left: 0, right: 0,
        padding: spacing.lg, paddingBottom: 30,
        backgroundColor: '#FFF', borderTopWidth: 1, borderTopColor: colors.border,
    },
    saveBtn: {
        height: 52, backgroundColor: colors.primary, borderRadius: radius.md,
        flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10,
        shadowColor: colors.primary, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 8, elevation: 6,
    },
    saveBtnText: { color: '#FFF', fontSize: 16, fontWeight: '700' },
    btnDisabled: { backgroundColor: '#CBD5E1', shadowOpacity: 0, elevation: 0 },
    errorContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 20, gap: 16 },
    errorText: { color: colors.muted, fontSize: 16, textAlign: 'center' },
    backBtn: { padding: 12, backgroundColor: colors.primary, borderRadius: radius.md },
    backBtnText: { color: '#FFF', fontWeight: '700' },
});
